openapi: "3.0.0"
info:
  version: 1.0.0
  title: TranslateApp API
  description: A simple API to illustrate OpenAPI concepts

servers:
  - url: https://localhost:8080

paths:
  /languages:
    get:
      description: Returns a list of languages
      #  ----- Added lines  ----------------------------------------
      responses:
        '200':
          description: Successfully returned a list of languages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string

        '500':
            description: Internal Server Error
      #  ---- /Added lines  ----------------------------------------
      
  /translate:
    post:
      summary: Creates a translation.
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  source:
                    type: string
                  target:
                    type: string
                  word:
                    type: string
      responses: 
        '200':
            description: Created
        '500':
            description: Internal Server Error
